FROM pensiero/apache-php-mysql

# Labels
LABEL maintainer "oscar.fanelli@gmail.com"

# PHP.ini file: enable <? ?> tags and quiet logging
RUN sed -i "s/display_errors = .*/display_errors = On/" $PHP_INI && \
    sed -i "s/display_startup_errors = .*/display_startup_errors = On/" $PHP_INI && \
    sed -i "s/error_reporting = .*/error_reporting = E_ALL | E_STRICT/" $PHP_INI

# Cleanup
RUN apt-get autoremove -yqq

# VirtualHost
COPY config/docker/apache-virtualhost.conf /etc/apache2/sites-available/000-default.conf

# Remove pre-existent apache pid and start apache
CMD rm -f $APACHE_PID_FILE && ./config/docker/start/development.sh