version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/docker/certs:/etc/nginx/certs

  web:
    build: .
    environment:
      - VIRTUAL_HOST=*.oscarfanelli.dev